id: PC1821405
initial_creation_type: input
source_metadata:
  Title: Yaśodharā Caritam
  Editor: Bhikkhu Pasadika and Bhiksu Tampalawela Dhammaratana
  Publisher: Bulletin d'etudes indiennesouvrage publie avec le concours de l'universite
    de Paris-III
  Place of Publication: Paris
  Year: '2003'
  Yaśodharācaritam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:35:40.647605'
last_modified_at: '2022-03-08T16:35:40.647614'
